import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const BebasNeue = localFont({
  src: "./fonts/BebasNeue-Regular.ttf",
  variable: "--font-bebas",
  weight: "100 900",
});
const workSans = localFont({
  src: "./fonts/WorkSans-VariableFont_wght.ttf",
  variable: "--font-work",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${BebasNeue.variable} ${workSans.variable} antialiased bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
